import 'package:freezed_annotation/freezed_annotation.dart';

part 'auth_user.freezed.dart';

/// Domain representation of an authenticated user.
///
/// Pure value type with `==`, `hashCode`, `copyWith`, and `toString`
/// generated by freezed. Intentionally **does not** implement
/// `fromJson` / `toJson` — domain entities never cross the wire; the
/// data layer translates between wire DTOs and this entity via
/// `AuthMapper`.
@freezed
abstract class AuthUser with _$AuthUser {
  const factory AuthUser({required String id, required String email}) =
      _AuthUser;
}
