import 'package:freezed_annotation/freezed_annotation.dart';

part 'todo_dto.freezed.dart';
part 'todo_dto.g.dart';

/// Wire-format representation of a Todo. Mirrors the API/JSON payload and
/// is decoupled from the domain `Todo` so we can evolve them independently.
///
/// `fromJson` / `toJson` are generated by `json_serializable`. The
/// `created_at` snake_case field is mapped via `@JsonKey`.
@freezed
class TodoDto with _$TodoDto {
  const factory TodoDto({
    required String id,
    required String title,
    @Default(false) bool completed,
    @JsonKey(name: 'created_at') DateTime? createdAt,
  }) = _TodoDto;

  factory TodoDto.fromJson(Map<String, dynamic> json) =>
      _$TodoDtoFromJson(json);
}
