import 'package:freezed_annotation/freezed_annotation.dart';

part 'todo.freezed.dart';

/// Domain entity for a Todo item.
///
/// Pure value type with `==`, `hashCode`, `copyWith`, and `toString`
/// generated by freezed. Intentionally **does not** implement
/// `fromJson` / `toJson` — domain entities never cross the wire; the
/// data layer translates between `TodoDto` (wire format) and this
/// entity via `todo_mapper.dart`.
@freezed
class Todo with _$Todo {
  const factory Todo({
    required String id,
    required String title,
    required bool completed,
    DateTime? createdAt,
  }) = _Todo;
}